import type { INodeProperties } from 'n8n-workflow';

// Input channels of a movement (core/fideltour/movement.py). For BE, PMS and
// WiFi companies HDH overwrites this value server-side; other company types
// can set it freely.
const inputChannelOptions = [
	{ name: 'Agency', value: 28 },
	{ name: 'API', value: 5 },
	{ name: 'App', value: 2 },
	{ name: 'BE Others', value: 16 },
	{ name: 'BE Restaurant', value: 17 },
	{ name: 'BE SPA', value: 18 },
	{ name: 'Booking Engine', value: 7 },
	{ name: 'Call Center', value: 10 },
	{ name: 'Channel Manager', value: 12 },
	{ name: 'Chatbot', value: 8 },
	{ name: 'Concierge', value: 9 },
	{ name: 'Connector Hub', value: 19 },
	{ name: 'CRM', value: 21 },
	{ name: 'Digital Key Platform', value: 20 },
	{ name: 'DMC', value: 29 },
	{ name: 'Import', value: 6 },
	{ name: 'Phone', value: 0 },
	{ name: 'PMS', value: 4 },
	{ name: 'PMS Others', value: 13 },
	{ name: 'PMS Restaurant', value: 14 },
	{ name: 'PMS SPA', value: 15 },
	{ name: 'POS Restaurant', value: 23 },
	{ name: 'POS SPA', value: 24 },
	{ name: 'Social Media Form', value: 22 },
	{ name: 'TTOO', value: 25 },
	{ name: 'Web', value: 1 },
	{ name: 'WiFi', value: 3 },
];

// Optional movement (entry) fields, shared by Create and Update.
// Field names match the HDH entries API (POST/PATCH /api/v1/entries/).
export const movementOptionalFields: INodeProperties[] = [
	{
		displayName: 'Adults',
		name: 'adults',
		type: 'number',
		typeOptions: { minValue: 0 },
		default: 0,
		routing: { send: { type: 'body', property: 'adults' } },
	},
	{
		displayName: 'Agency',
		name: 'agency',
		type: 'string',
		default: '',
		description: 'ID or name of the agency (created if it does not exist)',
		routing: { send: { type: 'body', property: 'agency' } },
	},
	{
		displayName: 'Amount',
		name: 'amount',
		type: 'number',
		default: 0,
		description: 'Total amount of the movement',
		routing: { send: { type: 'body', property: 'amount' } },
	},
	{
		displayName: 'Amount Paid',
		name: 'amountPaid',
		type: 'number',
		default: 0,
		routing: { send: { type: 'body', property: 'amount_paid' } },
	},
	{
		displayName: 'Babies',
		name: 'babies',
		type: 'number',
		typeOptions: { minValue: 0 },
		default: 0,
		routing: { send: { type: 'body', property: 'babies' } },
	},
	{
		displayName: 'Booking Type',
		name: 'bookingType',
		type: 'number',
		typeOptions: { minValue: 0 },
		default: 0,
		description:
			'Type of movement: 0=Booking (default), 1=Stay, 2=Visitor, 3=Other, 4=Restaurant table, 5=Gym/SPA access... See the HDH movements documentation for the full list.',
		routing: { send: { type: 'body', property: 'booking_type' } },
	},
	{
		displayName: 'Category',
		name: 'category',
		type: 'string',
		default: '',
		description: 'Name of the category of the movement (created if it does not exist)',
		routing: { send: { type: 'body', property: 'category' } },
	},
	{
		displayName: 'Checkin Realized',
		name: 'isCheckinRealized',
		type: 'boolean',
		default: false,
		description: 'Whether the check-in of the movement has been performed',
		routing: { send: { type: 'body', property: 'is_checkin_realized' } },
	},
	{
		displayName: 'Checkout Realized',
		name: 'isCheckoutRealized',
		type: 'boolean',
		default: false,
		description: 'Whether the check-out of the movement has been performed',
		routing: { send: { type: 'body', property: 'is_checkout_realized' } },
	},
	{
		displayName: 'Children',
		name: 'children',
		type: 'number',
		typeOptions: { minValue: 0 },
		default: 0,
		routing: { send: { type: 'body', property: 'children' } },
	},
	{
		displayName: 'Contracted Regime',
		name: 'contractedRegime',
		type: 'string',
		default: '',
		description: 'Code or name of the contracted regime (created if it does not exist)',
		routing: { send: { type: 'body', property: 'contracted_regime' } },
	},
	{
		displayName: 'Contracted Room Type',
		name: 'contractedRoomType',
		type: 'string',
		default: '',
		description: 'Code or name of the contracted room type (created if it does not exist)',
		routing: { send: { type: 'body', property: 'contracted_room_type' } },
	},
	{
		displayName: 'Currency',
		name: 'currency',
		type: 'string',
		default: '',
		placeholder: 'EUR',
		description: 'Currency in ISO 4217',
		routing: { send: { type: 'body', property: 'currency' } },
	},
	{
		displayName: 'Custom Fields (JSON)',
		name: 'customFields',
		type: 'json',
		default: '{}',
		description: 'Key-value object with Fideltour custom field IDs, e.g. {"cf_promo_code": "SUMMER24"}',
		routing: {
			send: {
				type: 'body',
				property: 'custom_fields',
				value: '={{ JSON.parse($value) }}',
			},
		},
	},
	{
		displayName: 'Event Type',
		name: 'eventType',
		type: 'string',
		default: '',
		description: 'Name of the event type of the movement (created if it does not exist)',
		routing: { send: { type: 'body', property: 'event_type' } },
	},
	{
		displayName: 'External Object ID',
		name: 'externalObjectId',
		type: 'string',
		default: '',
		description: 'ID of the movement in the external system, used for deduplication',
		routing: { send: { type: 'body', property: 'external_object_id' } },
	},
	{
		displayName: 'Fare Type',
		name: 'fareType',
		type: 'string',
		default: '',
		description: 'Name of the fare type (created if it does not exist)',
		routing: { send: { type: 'body', property: 'fare_type' } },
	},
	{
		displayName: 'Input Channel',
		name: 'inputChannel',
		type: 'options',
		options: inputChannelOptions,
		default: 5,
		description:
			'Input channel of the movement. For BE, PMS and WiFi companies HDH overwrites it server-side.',
		routing: { send: { type: 'body', property: 'input_channel' } },
	},
	{
		displayName: 'Juniors',
		name: 'juniors',
		type: 'number',
		typeOptions: { minValue: 0 },
		default: 0,
		routing: { send: { type: 'body', property: 'juniors' } },
	},
	{
		displayName: 'Notes',
		name: 'notes',
		type: 'string',
		default: '',
		routing: { send: { type: 'body', property: 'notes' } },
	},
	{
		displayName: 'Offer',
		name: 'offer',
		type: 'string',
		default: '',
		description: 'Name of the offer (created if it does not exist)',
		routing: { send: { type: 'body', property: 'offer' } },
	},
	{
		displayName: 'Original Input Channel',
		name: 'originalInputChannel',
		type: 'options',
		options: inputChannelOptions,
		default: 5,
		description: 'Original input channel of the movement, before any intermediary',
		routing: { send: { type: 'body', property: 'original_input_channel' } },
	},
	{
		displayName: 'Package',
		name: 'package',
		type: 'string',
		default: '',
		description: 'Name of the package of the movement (created if it does not exist)',
		routing: { send: { type: 'body', property: 'package' } },
	},
	{
		displayName: 'Paid',
		name: 'paid',
		type: 'boolean',
		default: false,
		description: 'Whether the full payment is confirmed',
		routing: { send: { type: 'body', property: 'paid' } },
	},
	{
		displayName: 'Regime',
		name: 'regime',
		type: 'string',
		default: '',
		description: 'Name of the regime (created if it does not exist)',
		routing: { send: { type: 'body', property: 'regime' } },
	},
	{
		displayName: 'Room Number',
		name: 'roomNumber',
		type: 'string',
		default: '',
		routing: { send: { type: 'body', property: 'room_number' } },
	},
	{
		displayName: 'Room Type',
		name: 'roomType',
		type: 'string',
		default: '',
		description: 'Name of the room type (created if it does not exist)',
		routing: { send: { type: 'body', property: 'room_type' } },
	},
	{
		displayName: 'Status',
		name: 'status',
		type: 'options',
		options: [
			{ name: 'Active', value: 1 },
			{ name: 'Inactive', value: 0 },
		],
		default: 1,
		routing: { send: { type: 'body', property: 'status' } },
	},
	{
		displayName: 'Sub Status',
		name: 'subStatus',
		type: 'options',
		options: [
			{ name: 'Cancelled', value: 4 },
			{ name: 'Checked Out', value: 9 },
			{ name: 'Confirmed', value: 2 },
			{ name: 'Modified', value: 6 },
			{ name: 'No Show', value: 5 },
			{ name: 'Pending', value: 3 },
			{ name: 'Quotation', value: 7 },
			{ name: 'Staying', value: 8 },
			{ name: 'Voided', value: 1 },
		],
		default: 2,
		routing: { send: { type: 'body', property: 'sub_status' } },
	},
	{
		displayName: 'Upgraded Regime',
		name: 'upgradedRegime',
		type: 'string',
		default: '',
		description: 'Code or name of the upgraded regime (created if it does not exist)',
		routing: { send: { type: 'body', property: 'upgraded_regime' } },
	},
	{
		displayName: 'Upgraded Room Type',
		name: 'upgradedRoomType',
		type: 'string',
		default: '',
		description: 'Code or name of the upgraded room type (created if it does not exist)',
		routing: { send: { type: 'body', property: 'upgraded_room_type' } },
	},
	{
		displayName: 'URL',
		name: 'url',
		type: 'string',
		default: '',
		description: 'URL associated to the movement, usable in campaigns via [BOOKING_URL]',
		routing: { send: { type: 'body', property: 'url' } },
	},
];
