import type { INodeProperties } from 'n8n-workflow';

// Optional contact profile fields, shared by Create and Update.
// Field names match the HDH contacts API (POST/PATCH /api/v1/contacts/).
export const contactProfileFields: INodeProperties[] = [
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		default: '',
		routing: { send: { type: 'body', property: 'name' } },
	},
	{
		displayName: 'Surname',
		name: 'surname',
		type: 'string',
		default: '',
		routing: { send: { type: 'body', property: 'surname' } },
	},
	{
		displayName: 'Phone',
		name: 'phone1',
		type: 'string',
		default: '',
		routing: { send: { type: 'body', property: 'phone1' } },
	},
	{
		displayName: 'Phone 2',
		name: 'phone2',
		type: 'string',
		default: '',
		description: 'Secondary phone number of the contact',
		routing: { send: { type: 'body', property: 'phone2' } },
	},
	{
		displayName: 'Birthday',
		name: 'birthday',
		type: 'string',
		default: '',
		placeholder: 'YYYY-MM-DD',
		routing: { send: { type: 'body', property: 'birthday' } },
	},
	{
		displayName: 'Gender',
		name: 'gender',
		type: 'options',
		options: [
			{ name: 'Not Specified', value: 0 },
			{ name: 'Male', value: 1 },
			{ name: 'Female', value: 2 },
			{ name: 'Non-Binary', value: 3 },
			{ name: 'Gender Fluid', value: 4 },
			{ name: 'Prefers Not to Say', value: 5 },
		],
		default: 0,
		routing: { send: { type: 'body', property: 'gender' } },
	},
	{
		displayName: 'Identification Document Type',
		name: 'identificationDocumentType',
		type: 'options',
		options: [
			{ name: 'DNI', value: 1 },
			{ name: 'NIE', value: 2 },
			{ name: 'Other', value: 0 },
			{ name: 'Passport', value: 3 },
		],
		default: 0,
		description: 'Type of document that identifies the contact',
		routing: { send: { type: 'body', property: 'identification_document_type' } },
	},
	{
		displayName: 'Identification Number',
		name: 'identificationNumber',
		type: 'string',
		default: '',
		description: 'Number of the identification document of the contact',
		routing: { send: { type: 'body', property: 'identification_number' } },
	},
	{
		displayName: 'Language',
		name: 'language',
		type: 'string',
		default: '',
		placeholder: 'es',
		description: 'ISO 639-1 code',
		routing: { send: { type: 'body', property: 'language' } },
	},
	{
		displayName: 'Country',
		name: 'country',
		type: 'string',
		default: '',
		placeholder: 'ES',
		description: 'ISO 3166-1 alpha-2 code',
		routing: { send: { type: 'body', property: 'country' } },
	},
	{
		displayName: 'Address',
		name: 'address',
		type: 'string',
		default: '',
		routing: { send: { type: 'body', property: 'address' } },
	},
	{
		displayName: 'Post Code',
		name: 'postCode',
		type: 'string',
		default: '',
		routing: { send: { type: 'body', property: 'post_code' } },
	},
	{
		displayName: 'Province',
		name: 'province',
		type: 'string',
		default: '',
		description: 'ID or name of the province (created if it does not exist)',
		routing: { send: { type: 'body', property: 'province' } },
	},
	{
		displayName: 'Town',
		name: 'town',
		type: 'string',
		default: '',
		description: 'ID or name of the town (created if it does not exist)',
		routing: { send: { type: 'body', property: 'town' } },
	},
	{
		displayName: 'Zone',
		name: 'zone',
		type: 'string',
		default: '',
		description: 'ID or name of the zone (created if it does not exist)',
		routing: { send: { type: 'body', property: 'zone' } },
	},
	{
		displayName: 'Business Name',
		name: 'businessName',
		type: 'string',
		default: '',
		description: 'Name of the company the contact works for',
		routing: { send: { type: 'body', property: 'business_name' } },
	},
	{
		displayName: 'Work Place',
		name: 'workPlace',
		type: 'string',
		default: '',
		description: 'Position or department of the contact in their company',
		routing: { send: { type: 'body', property: 'work_place' } },
	},
	{
		displayName: 'Business Address',
		name: 'businessAddress',
		type: 'string',
		default: '',
		routing: { send: { type: 'body', property: 'business_address' } },
	},
	{
		displayName: 'Fiscal Address',
		name: 'fiscalAddress',
		type: 'string',
		default: '',
		routing: { send: { type: 'body', property: 'fiscal_address' } },
	},
	{
		displayName: 'Custom Tags',
		name: 'customTags',
		type: 'string',
		default: '',
		description: 'Comma-separated list of tag IDs or names (created if they do not exist)',
		routing: {
			send: {
				type: 'body',
				property: 'custom_tags',
				value: '={{ $value.split(",").map(tag => tag.trim()).filter(tag => tag) }}',
			},
		},
	},
	{
		displayName: 'Custom Fields (JSON)',
		name: 'customFields',
		type: 'json',
		default: '{}',
		description: 'Key-value object with Fideltour custom field IDs, e.g. {"cf_vip": true}',
		routing: {
			send: {
				type: 'body',
				property: 'custom_fields',
				value: '={{ JSON.parse($value) }}',
			},
		},
	},
	{
		displayName: 'External Object ID',
		name: 'externalObjectId',
		type: 'string',
		default: '',
		description: 'ID of the contact in the external system, used for deduplication',
		routing: { send: { type: 'body', property: 'external_object_id' } },
	},
	{
		displayName: 'Notes',
		name: 'notes',
		type: 'string',
		default: '',
		routing: { send: { type: 'body', property: 'notes' } },
	},
	{
		displayName: 'Subscribed',
		name: 'subscribed',
		type: 'boolean',
		default: false,
		description: 'Whether the contact is subscribed to mailing',
		routing: { send: { type: 'body', property: 'subscribed' } },
	},
];

// Source of the contact (required on create). Values from the HDH contacts API.
export const contactSourceField: INodeProperties = {
	displayName: 'Source',
	name: 'source',
	type: 'options',
	options: [
		{ name: 'API', value: 21 },
		{ name: 'Booking Engine / Web', value: 3 },
		{ name: 'Call Center', value: 12 },
		{ name: 'Chatbot', value: 10 },
		{ name: 'Concierge', value: 11 },
		{ name: 'Contact Form', value: 7 },
		{ name: 'CRM', value: 24 },
		{ name: 'Guest Portal', value: 8 },
		{ name: 'Import', value: 5 },
		{ name: 'Landing Form', value: 13 },
		{ name: 'Newsletter Form', value: 6 },
		{ name: 'Other', value: 4 },
		{ name: 'PMS', value: 0 },
		{ name: 'Pre-Checkin', value: 9 },
		{ name: 'WiFi Login', value: 1 },
		{ name: 'Zapier / Make / N8n', value: 22 },
	],
	default: 21,
	description: 'Origin of the contact',
	routing: { send: { type: 'body', property: 'source' } },
};
